services:
  integration:
    build:
      context: .
      target: integration-test
    command:
      [
        "dotnet",
        "test",
        "src/test/PostService.Integration",
        "--configuration",
        "Release",
      ]
