name: CI

on:
  push:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run unit-test target
        run: docker build -t build --progress=plain --no-cache --target unit-test .

  integration-test:
    if: github.event_name == 'pull_request'
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f compose.integration.yaml up --build --abort-on-container-exit --exit-code-from integration
